### ISSUE TITLE
Maven artifact group id.

### ISSUE THREAD

**Issue by mattak** [chsh/geohex4j#6]
I tried to upload geohex4j library on the issue https://issues.sonatype.org/browse/OSSRH-17037.

Then operator said.

> Do you or your organization own the domain geohex.net? If not, please read:
> http://central.sonatype.org/pages/choosing-your-coordinates.html
> You may also choose a groupId that reflects your project hosting, in this case, something like com.github.chsh

I thought public domain "geohex.net" is owned by @sa2da.

So what should we do..?

I think the best thing is asking him to allow to use the group id..

**Comment by chsh** [comment]
How about to use "org.geohex"?
Our module is listed on http://www.geohex.org/ It may be an evidence of domain ownership.

**Comment by sa2da** [comment]
Hi Takuma,

It's difficult to reply soon cause I'm not familiar with this repository
management system.
But the thing is that the Group ID should be unique he said, so whichever
else .org or .net you would use, it might not be a proper structure in this
case.
So, at present, I would suggest you follow his comment.
Also, I'm not sure but if it work for you with a subdomain like
"org.geohex.java", I can make add for you.
Let me know the ideal way.

Thanks,
sa2da

2015-08-10 18:01 GMT-07:00 Takuma Maruyama <notifications@github.com>:

**Comment by mattak** [comment]
Thanks for reply.

org.geohex is sounds good and it's subdomain is better.
So how about using org.geohex.geohex4j?
I think it's the best. There is two reason.

1. minimize the authority of uploading.
2. group id which contains project name is more better for searching. (http://d.hatena.ne.jp/gfx/20140519/1400451633)

Once we upload to maven central, groupId authority is only for uploaded owner.
If we upload the module as group id "org.geohex", then we can upload any other subdomain such as "org.geohex.geohex4scala" or "org.geohex.geohex4kotlin".
It prohibit to upload another module developer using maven central.

**Comment by sa2da** [comment]
Sorry for the late reply. I agree u use org.geohex.geohex4j, but let me
know if you need my help when need exclusive domain of "org.geohex".


2015-08-11 19:10 GMT-07:00 Takuma Maruyama <notifications@github.com>:

**Comment by mattak** [comment]
Thanks!
I'll resume submission work.

**Comment by mattak** [comment]
Group id was prepared. now we able to upload artifact as 'org.geohex.geohex4j'

**Comment by chsh** [comment]
:+1:
